### ISSUE TITLE
Brightness widget

### ISSUE THREAD

**Issue by xkaira** [lcpz/lain#365]
Hello,
im struggling with creating brightness widget using alsabar.lua as a template. Unfortunately my programming knowledge is non existent at its best. Before trying copy/paste and rough edit (with miserably results, no surprise here) i have try'ed every single brightness widget i could find. None of theme worked, which is actually strange, because xbacklight on my system works without any problem. What i would want:

- widget capable of reading from xbacklight command
- showing output as % of brightness

I think, that having working base i could propably make the rest (working progressbar, widgetbuttons and some form of update request).
If any of more knowledgeable person could help, it would mean very much to me (couple of days struggling already...).

**Comment by lcpz** [comment]
What you ask is very simple to achieve, and `lain` is not needed either.

I'm a desktop user, so you need to give me an output example of `xbacklight -get` and the range of possible values.

**Comment by xkaira** [comment]
xbacklight -get output: 
- example: 50.000000
- min value: 0.000000
- max value: 100.000000

Well, after my plays with awesome i considered, that i should learn some basic things about scripting (or any at that matter) programming language. Nonetheless i must say, that awesome with lain are pure piece of art. 
Thank you in advance for you're help.

**Comment by lcpz** [comment]
There you go. I can't test it, so tell me if it works.

```lua
-- progressbar
local backlight_bar = wibox.widget {
    max_value     = 1,
    forced_height = 20,
    forced_width  = 100,
    shape         = gears.shape.rounded_bar,
    border_width  = 2,
    widget        = wibox.widget.progressbar,
}

-- text widget (which also updates the progressbar)
local backlight = awful.widget.watch("xbacklight -get", 10,
    function(widget, stdout)
        local perc = tonumber(stdout:match("(%d+).%d"))
        widget:set_text("Brightness: "..perc.."%")
        backlight_bar:set_value(perc/100)
    end
)
```

Add one or both to your favourite wibar.

Read [here](https://awesomewm.org/doc/api/classes/wibox.widget.progressbar.html) to know how to customise your progressbar, and [here](https://awesomewm.org/doc/api/classes/wibox.widget.textbox.html) for the textbox widget. In both pages, you can also find out how to attach buttons.

**Comment by xkaira** [comment]
It works tremendously. Thank you very much. I modified it a little to match my little colorized Rainbow theme. Of course i have read awesome API documentation (I have it in bookmarks).  The main problem I have is my lack of IT knowledge and very few examples of syntax usage on already mentioned awesome API site. Now the code looks like:
```
--Brightness
local backlight_bar = wibox.widget {
    max_value     = 1,
    color = theme.fg_widget,
     background_color = theme.bg_widget,
	forced_height = 1,
    forced_width  = 50,
    margins          = 1,
    paddings         = 1,
    ticks            = true,
    ticks_size       = 7,
    widget        = wibox.widget.progressbar,
}
-- text widget (which also updates the progressbar)
local backlight = awful.widget.watch("xbacklight -get", 60,
    function(widget, stdout)
        local perc = tonumber(stdout:match("(%d+).%d"))
        backlight_bar.tooltip:set_text("Brightness: "..perc.."%")
   --    widget:set_text("Brightness: "..perc.."%")
        backlight_bar:set_value(perc/100)
    end
)
backlight_bar:buttons(awful.util.table.join (
          awful.button({}, 1, function() awful.spawn("xbacklight =100") end),
          awful.button({}, 3, function() awful.spawn("xbacklight =0") end),
          awful.button({}, 4, function() awful.spawn("xbacklight +20") end),
           awful.button({}, 5, function() awful.spawn("xbacklight -20") end)
))
backlight_bar.tooltip = awful.tooltip({ objects = { backlight_bar } })
local lightbg = wibox.container.background(backlight_bar, "#585858", gears.shape.rectangle)
local lightwidget = wibox.container.margin(lightbg, 7, 7, 5, 5)
lighticon = wibox.widget.textbox("&#xf0eb;  ")
lighticon:set_font("FontAwesome `9")
```
, and here is the result:

![Image of screenshot](https://image.ibb.co/cadVvb/20171003_012651.jpg)

Once again: Thank you.

**Comment by lcpz** [comment]
> The main problem I have is my lack of IT knowledge and very few examples of syntax usage on already mentioned awesome API site.

It's normal, Awesome has a steep learning curve if you're not familiar with programming or WMs. But the time you invest is not wasted, since it'll get you a full control on your working environment. You'll also learn some useful skills in the process.

Anyway, the current result looks good to me. 😃

**Comment by lcpz** [comment]
PS: If you don't use the text widget, you can also replace it with a simple timer:

```lua
local backlight_timer = gears.timer {
    timeout   = 60,
    autostart = true,
    callback  = function()
        awful.spawn.easy_async("xbacklight -get",
            function(stdout)
                local perc = tonumber(stdout:match("(%d+).%d"))
                backlight_bar.tooltip:set_text("Brightness: "..perc.."%")
                backlight_bar:set_value(perc/100)
            end
        )
    end
}
```

**Comment by xkaira** [comment]
Of course it's also works as a charm. But if you are still intendent to help, i would have one more question.
Let's say, that i don't really need a system, that will be checking value after fixed time period, but rather system that check value at the start of the wm, and then updates it after meeting some conditions (shortcuts changing brightness).
Using backlight_timer makes that the widget bar and tooltip get first information after one minute (timeout time). I tried to change it, taking some parts of you're alsabar as example. I manage to make someting like this:
```lua

function backlight_update()
local backlight_timer = 
        awful.spawn.easy_async("xbacklight -get",
            function(stdout)
                local perc = tonumber(stdout:match("(%d+).%d"))
                backlight_bar.tooltip:set_text("Brightness: "..perc.."%")
                backlight_bar:set_value(perc/100)
            end
        )
    end

backlight_bar:buttons(awful.util.table.join (
          awful.button({}, 1, function() awful.spawn("xbacklight =100") backlight_update() end),
          awful.button({}, 3, function() awful.spawn("xbacklight =0") backlight_update() end),
          awful.button({}, 4, function() awful.spawn("xbacklight +20") backlight_update() end),
          awful.button({}, 5, function() awful.spawn("xbacklight -20") backlight_update() end)
))
```
It starts the bar correctly (with proper tooltip), unfortunetly, using the shortcuts makes the bar behave incorrectly. After first use, there are no changes, and after each next it seems like there is one step lag.
I hope that i explained it correctly (as it can be seen on previous desktop screenshot, english isn't my native language).

Edit: It looks like the backlight_update function propably have had been executed too fast, so it reads old or only partly changed value. Dirty workaround like this fixed it:
```lua
function sleep(s)
  local ntime = os.clock() + s
  repeat until os.clock() > ntime
end

function backlight_update()
local backlight_timer = 
        awful.spawn.easy_async("xbacklight -get",
            function(stdout)
                local perc = tonumber(stdout:match("(%d+).%d"))
                backlight_bar.tooltip:set_text("Brightness: "..perc.."%")
                backlight_bar:set_value(perc/100)
            end
        )
    end

backlight_update() --executed once (i hope) on awesomewm start

backlight_bar:buttons(awful.util.table.join (
          awful.button({}, 1, function() awful.spawn("xbacklight =100") sleep(1) backlight_update() end),
          awful.button({}, 3, function() awful.spawn("xbacklight =0") sleep(1) backlight_update() end),
          awful.button({}, 4, function() awful.spawn("xbacklight +25") sleep(1) backlight_update() end),
          awful.button({}, 5, function() awful.spawn("xbacklight -25") sleep(1) backlight_update() end)
))
```
Maybe updating proces isn't too much fluent, but it works.
Of course if there is any way to do it more cleanly, it would be terrific.

**Comment by lcpz** [comment]
```lua
--{{ Brightness widget
local backlight_bar = wibox.widget {
    max_value        = 1,
    color            = theme.fg_widget,
    background_color = theme.bg_widget,
    forced_height    = 1,
    forced_width     = 50,
    margins          = 1,
    paddings         = 1,
    ticks            = true,
    ticks_size       = 7,
    widget           = wibox.widget.progressbar
}

local backlight_timer = gears.timer {
    timeout   = 60,
    autostart = true,
    callback  = function()
        awful.spawn.easy_async("xbacklight -get",
            function(stdout)
                local perc = tonumber(stdout:match("(%d+).%d"))
                backlight_bar.tooltip:set_text("Brightness: "..perc.."%")
                backlight_bar:set_value(perc/100)
            end
        )
    end
}

backlight_timer:emit_signal("timeout") -- execute once on startup

backlight_bar:buttons(awful.util.table.join (
    awful.button({}, 1, function()
        awful.spawn("xbacklight =100")
        backlight_timer:emit_signal("timeout")
     end),
    awful.button({}, 3, function()
        awful.spawn("xbacklight =0")
        backlight_timer:emit_signal("timeout")
     end),
    awful.button({}, 4, function()
        awful.spawn("xbacklight +25")
        backlight_timer:emit_signal("timeout")
     end),
    awful.button({}, 5, function()
        awful.spawn("xbacklight -25")
        backlight_timer:emit_signal("timeout")
     end)
))
--}}
