### ISSUE TITLE
Net module stopped working

### ISSUE THREAD

**Issue by kajzersoze** [lcpz/lain#378]
$ awesome -v
```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.0
```

$ lua -v
`Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio`

Today I upgraded kernel from 4.12.12 to 4.14.10 and net module stopped working for some reason, it just displays 0.0 for both upload and download, network is working fine so it's something in the lain net module, can't figure out what.
If I boot into kernel 4.12.12 then it's fine.

**Comment by kajzersoze** [comment]
When I replaced %s with enp2s0 it started to work.
It is something in kernel, though version doesn't matter, the way it's compiled does, don't know what exactly but some security measures I guess, anyway that's another story.

**Comment by lcpz** [comment]
https://github.com/lcpz/lain/wiki/net#setting-iface-manually

**Comment by kajzersoze** [comment]
What confused me was no "no carrier" notification, instead it was 0.0
