### ISSUE TITLE
Calendar widget sometimes doesn't hide

### ISSUE THREAD

**Issue by unode** [lcpz/lain#379]
I have a dual monitor setup. The second monitor is setup above the primary.

All screens have their own widget bar at the top of each monitor and are configured using:
```lua
awful.screen.connect_for_each_screen(function(s)
...
```
-------------

When moving the mouse cursor from one screen to the next (usually bottom to top) over the calendar widget, the floating calendar sometimes remains visible as if the widget was still being hovered.
When this happens, the floating calendar will only vanish if I either click on the floating window or if the mouse hovers one of the two textclock widgets (one on each monitor).
With other widgets (e.g. `fs`) something similar happens but the floating window vanishes as soon as any widget is hovered or when the mouse moves to a different screen.

I generally initialize widgets with this kind of code pattern:
```lua
local fsicon = wibox.widget.imagebox(theme.widget_hdd)
local fswidget = lain.widget.fs({
    followtag = true,
    ...
})

awful.screen.connect_for_each_screen(function(s)
    s.mywibox:setup {
        ...
        {
            layout = wibox.layout.fixed.horizontal,
            fsicon, fswidget.widget,
        ...
```

With calendar I have to use `attach_to`:

```lua
local mytextclock = wibox.widget.textclock("%a %d/%m/%Y, %H:%M", 10)

lain.widget.calendar({
    attach_to = { mytextclock },
    followtag = true,
    ...
})
```
because the `factory` function of `calendar` doesn't return anything.

The wiki incorrectly mentions:
```
local calendar = lain.widget.calendar()
```
In this case, `calendar` is `nil`.

Given the above, is there any chance that calendar's `factory` is modified to behave the same as other widgets? I suspect this alone might be sufficient to address the sticky issues I'm experiencing.

While the 'not hiding' behavior might be an issue with awesome, the fact that the calendar behaves differently from other widgets might be explained by the use of `attach_to`.

**Comment by lcpz** [comment]
> the fact that the calendar behaves differently from other widgets might be explained by the use of `attach_to`

Indeed: in order to make it behave like other widgets, we have to somehow duplicate `wibox.widget.textclock`, which is not desirable.

Also, note that [`awful.widget.calendar_popup`](https://awesomewm.org/doc/api/classes/awful.widget.calendar_popup.html) is built in the same way.

I've fixed the wiki. Do you still experience this issue?

**Comment by unode** [comment]
> Do you still experience this issue?

Yes, quite frequently.
Wouldn't say every time I move the mouse to a different screen but often enough to be annoying.

**Comment by lcpz** [comment]
I can either make `calendar` an object to be returned by the factory method as you suggested, thus changing the current API, or assert that calendar notifications are not displayed on unfocused screens. I don't see how the first option would solve it though.

But before deciding, please check if this happen on a single screen setup too.

**Comment by unode** [comment]
Just tried it. It doesn't happen easily but a few minutes of moving the mouse quickly on and off the widget made it happen twice.

**Comment by lcpz** [comment]
@unode New implementation is up. Please check `newcal` branch and tell me what do you think.

**Comment by unode** [comment]
Just tested and haven't hit any problem so far. Thanks for the update.
