### ISSUE TITLE
alsabar notifications don't work with a vertical wibar

### ISSUE THREAD

**Issue by sprnza** [lcpz/lain#384]
Hi!
Just found out, that alsabar notifications works only if alsabar is placed on a wibox becuase preset's text depends on mywibox.height. I've got a vertical wibar so it fails. 
I believe I need to rewrite this code in the notification_preset table somehow:

```
            int = math.modf((alsabar._current_level / 100) *     awful.screen.focused().mywibar.width)
            preset.text = string.format("[%s%s]", string.        rep("|", int),
                          string.rep(" ", awful.screen.focused().mywibar.width - int))
```

**Comment by sprnza** [comment]
Or it's not possible since I can't access _current_level outside alsabar definition?

**Comment by lcpz** [comment]
Please try 3136a45.

**Comment by sprnza** [comment]
Hi @lcpz ! It doesn't work because I don't have a wibox but a [wibar](https://awesomewm.org/doc/api/classes/awful.wibar.htm).

**Comment by lcpz** [comment]
It's the same, every `wibox` is an `awful.wibar`, as you can read [here](https://awesomewm.org/doc/api/classes/awful.wibar.html) (by the way, your link is 404).

So, you confirm that 3136a45 doesn't work for you? Please paste me your configurations (the whole vertical wibar code) and preferably the [X error log](https://github.com/lcpz/lain/blob/master/ISSUE_TEMPLATE.md#how-to-provide-x-error-log) of when the notification should be displayed.

**Comment by sprnza** [comment]
3136a45 doesn't work because it reffers to `mywibox` and I don't have it defined in my rc.lua. Here is the [errors](http://sh.speran.info/6). Actually I can't remember why I've renamed `mywibox` to `mywibar`. The problem that alsabar.lua is hardcoded to a variable name that could have an arbitrary value. Here is how my wibar is configured:
```
s.mywibar = awful.wibar({ position = "left", screen = s,     width = 46})
```

**Comment by lcpz** [comment]
In theory you might be right, it can be considered hardcoding.

But in practice it is not, since `mywibox` is a common variable, used also in the default `rc.lua`.

I'll come up with something to cope with your urge to change default variables. 😄
