### ISSUE TITLE
Can't install lain by luarocks: lain-git.rockspec error

### ISSUE THREAD

**Issue by DoKel** [lcpz/lain#390]
* output of `awesome -v` and `lua -v`
**$awesome -v**
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
**$lua -v**
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio

* expected behavior
As I can read from wiki, lain should be available from luarocks.
* actual behavior
It is not:
#luarocks install lain
Error: /tmp/luarocks_luarocks-rockspec-lain-git-hAI5vL/lain-git.rockspec: Type mismatch on field version: invalid value git does not match '[%w.]+-[%d]+'

Luarocks version is 2.4.3

* steps to reproduce the problem
Try to install lain by luarocks ;)

**Comment by lcpz** [comment]
Something is wrong in the `rockspec`.

@aajjbb Can you please give it a look?

**Comment by aajjbb** [comment]
I'll look into it as soon as I get home.

**Comment by aajjbb** [comment]
Luarocks now has a new rule for naming .rockspec files that are development versions. They should be called `scm` and no `git`. I've updated a new rockspec to Luarocks site following that rule. 

I'll update the new .rockspec file in a pr.
