### ISSUE TITLE
Mpd widget not showing cover art

### ISSUE THREAD

**Issue by Incognito4nonymous** [lcpz/lain#393]
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.2
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio

So I'm back after... This : 
https://github.com/lcpz/lain/issues/227

And I finally managed to make my way out of the version problems I faced back then, and I'm now back with all things patched up, but surprisingly enough, I still got the issue on my Slackware...

When I play music from an album, it will just display the track informations, but no cover art despite having created mpdcover.png/jpg in /tmp.

**Comment by lcpz** [comment]
The widget has changed since then.

There is no more external script to fetch the cover and put it into `/tmp`. Now the widget retrieves it directly from your music folders. Please read the [mpd](https://github.com/lcpz/lain/wiki/mpd) wiki again.

**Comment by Incognito4nonymous** [comment]
Oh, I'm not longer using the version that required the external script, I think it was mpdcover, I'm using a commit that's from june 2017, and it didn't used that anymore, anyway I updated the mpd widget to the latest commit, and still no cover art displaying despite the updates. So for some reason the issue is still ongoing...
My system is Slackware 14.2 64bits.

**Comment by lcpz** [comment]
Assuming that you've correctly set the [input table](https://github.com/lcpz/lain/wiki/mpd#input-table) and  that you have an image file in the album folder which is in the format `*.(jpg|jpeg|png|gif)$`, then the only possible issue is that [this `find`](https://github.com/lcpz/lain/blob/master/widget/mpd.lua#L111-L112) is not working for you. Try spawning the same command in the shell and see what it does on you machine.

Also, check if this happens because of special characters or not.

**Comment by lcpz** [comment]
Let's try in a different way. Put the following code in `lain/widget/mpd.lua` after [this line](https://github.com/lcpz/lain/blob/master/widget/mpd.lua#L112):

```lua
naughty.notify { text = cover, timeout = 0 }
```

Start mpd, play a song, and give me:

1. a screenshot of the notifications that will appear;
2. full path and `ls -A` of the album folder of the current song.

**Comment by Incognito4nonymous** [comment]
![tosend2018-05-10-223959_1366x768_scrot](https://user-images.githubusercontent.com/13099461/39890382-1d8f085a-548a-11e8-81a5-49074ddbddcd.png)

_Fatboy Slim - 10th and Crenshaw.mp3
Fatboy Slim - Everybody Needs A 303.mp3
Fatboy Slim - First Down.mp3
Fatboy Slim - Give The PoMan A Break.mp3
Fatboy Slim - Going Out of My Head.mp3
Fatboy Slim - Punk to Funk.mp3
Fatboy Slim - Santa Cruz Extended.mp3
Fatboy Slim - Song for Lindy.mp3
Fatboy Slim - The Sound of Milwaukee.mp3
Fatboy Slim - The Weekend Starts Here.mp3
_

/ntfs/Users/Incognito/Music/Fatboy Slim - Better Living Through Chemestry

Here

**Comment by lcpz** [comment]
As supposed, the `find` command doesn't get `cover.jpg`.

Try this command in shell, see how you can make it work to get such file.

```shell
find '/ntfs/Users/Incognito/Music/Fatboy Slim - Better Living Through Chemestry' -maxdepth 1 -type f | egrep -i -m1 '*.(jpg|jpeg|png|gif)$'
```

**Comment by Incognito4nonymous** [comment]
Here's the output 

/ntfs/Users/Incognito/Music/Fatboy Slim - Better Living Through Chemestry/cover.jpg

**Comment by lcpz** [comment]
Obviously something is lost on Lua side when parsing wildcards. Try setting `cover_pattern` input to `cover.jpg`, `cover.*`, or whatever pattern you can think of.

**Comment by Incognito4nonymous** [comment]
Heck, even tried to link it to a single file and it didn't worked... And yea, I have imagemagick installed... I really don't get it, it works out of the box on Debian...

**Comment by lcpz** [comment]
Imagemagick is not required anymore. The widget just need to grab the correct path.

I don't know what to think.

**Comment by lcpz** [comment]
@Incognito4nonymous Any updates on this?

**Comment by lcpz** [comment]
Could it be possible that the full path is right, but it needs to be escaped?

Try with directories and files that don't have whitespaces or special characters.

**Comment by Incognito4nonymous** [comment]
Still doesn't work, I already tried that a while ago and just also re-tried, again I tried on my Debian system and it works flawlessly, and I got the same Awesome configuration on both of em.

**Comment by Incognito4nonymous** [comment]
Pardon me, my mouse slipped and I pressed "Close and Comment" Rather than "Comment"

**Comment by lcpz** [comment]
You might try to find on reddit other Slackware users and see if they can replicate the issue.

Other than that, I don't know what to do here.

**Comment by Incognito4nonymous** [comment]
Back, but with Debian 9.6 making my machine run this time, running Awesome 4.2 compiled against Lua 5.3.3, and hum, seemingly it ain't Slackware specific, maybe has it something to do with the fact my music is stored in a ntfs partition ?
I'm definitely decided to get over this this time, there's nothing pushing me back anymore

**Comment by Incognito4nonymous** [comment]
An idea just striked me like a nuclear bomb. If it works on my raspberry pi that has the music folder in the user directory, what prevents it from working here must be the fact the music files are stored on another partition (NTFS one) the partition's format shouldn't be what causes a problem in my opinion, and I may have found a quick and dirty fix, I'm gonna see what happens if I replace my user music folder with a symlink pointing towards the desired repertory

**Comment by Incognito4nonymous** [comment]
It just worked ! I can't believe I resolved this issue by myself ! 
It should be added to wiki that it is preferable to create a symlink to the folder containing the music for the widget to function properly, closing the issue !

**Comment by lcpz** [comment]
You have edit rights for the wiki, can you please update it yourself, reporting the example of how you created the symlink in your specific case?

**Comment by lcpz** [comment]
I [updated](https://github.com/lcpz/lain/wiki/mpd#cover-not-showing-in-notifications) the wiki by myself.

**Comment by Incognito4nonymous** [comment]
Daym, I just received the mail now, you outran me.

**Comment by Incognito4nonymous** [comment]
There we go, just added a bit of detail about that case.
