### ISSUE TITLE
centerwork layout does not support mouse_resize_handler

### ISSUE THREAD

**Issue by p-himik** [lcpz/lain#395]
`centerwork` is great, and for most cases using `incmwfact` is fine, but it would be cool to also be able to change window sizes with a mouse. Apart from changing the main window width, I think it also makes it possible to change other windows' sizes.

**Comment by lcpz** [comment]
It seems that what you want is not related to a specific layout, but is general.

I do not understand what exactly you want to change and how, so I will list some possible actions: 

1. You can bind `incmwfact` to [mouse scroll buttons](https://awesomewm.org/doc/api/libraries/mouse.html).
2. You can change window factor per client in your `rc.lua`. This is an example with my [template](https://github.com/lcpz/awesome-copycats/blob/master/rc.lua.template):

    ```diff
    611c611,613
    <     awful.button({ modkey }, 3, awful.mouse.client.resize))
    ---
    >     awful.button({ modkey }, 3, awful.mouse.client.resize),
    >     awful.button({ modkey }, 4, function (c) awful.client.incwfact(0.1, c) end),
    >     awful.button({ modkey }, 5, function (c) awful.client.incwfact(-0.1, c) end))
    ```
3. You can adjust `beatiful.useless_gaps` [on the fly](https://github.com/lcpz/lain/wiki/Utilities#useless-gaps-resize).

**Comment by p-himik** [comment]
By `mouse_resize_handler` I meant a function in Awesome WM that handles mouse movement for client resizes. E.g. for the tile layout: https://github.com/awesomeWM/awesome/blob/458981710cd34527b05272b2b16d6b6402d18e1a/lib/awful/layout/suit/tile.lua#L48
It's used here: https://github.com/awesomeWM/awesome/blob/bed7abf5d1fa1ad7859dee3c8f9b2bc3d28b9d25/lib/awful/mouse/init.lua#L272
I thought that maybe it's something worth implementing in the `lain`'s layouts.

**Comment by lcpz** [comment]
I understand now, thank you.

Well, since these static layouts will be superseded by [dynamic layouts](https://github.com/awesomeWM/awesome/pull/644), spending time on them is futile.

But, we can just use a dirty hack. Put this in your `rc.lua`:

```lua
lain.layout.centerwork.mouse_resize_handler = awful.layout.suit.tile.mouse_resize_handler
```

If it does not work, replace `tile` with `magnifier` or `floating`.

Note that you should be able to resize only horizontally, since the height of the master client is maximised.

Also, note that you can do this trick with any `lain` layout.

**Comment by p-himik** [comment]
Ah, I did not know about dynamic layouts. Thanks for the link and the workaround!

**Comment by p-himik** [comment]
@lcpz Using existing `mouse_resize_handler` implementations did not work for a number of reasons. Here's what I've come up with:

```lua
local function centerwork_mouse_resize_handler(c, corner, x, y, orientation)
    local wa = c.screen.workarea
    local mwfact = c.screen.selected_tag.master_width_factor
    local g = c:geometry()
    local offset = 0
    local cursor = "cross"
    local corner_coords

    if orientation == 'vertical' then
        if g.height + 15 >= wa.height then
            offset = g.height * .5
            cursor = "sb_h_double_arrow"
        elseif not (g.y + g.height + 15 > wa.y + wa.height) then
            offset = g.height
        end
        corner_coords = { x = wa.x + wa.width * (1 - mwfact) / 2, y = g.y + offset }
    else
        if g.width + 15 >= wa.width then
            offset = g.width * .5
            cursor = "sb_v_double_arrow"
        elseif not (g.x + g.width + 15 > wa.x + wa.width) then
            offset = g.width
        end
        corner_coords = { y = wa.y + wa.height * (1 - mwfact) / 2, x = g.x + offset }
    end

    capi.mouse.coords(corner_coords)

    local prev_coords = {}
    capi.mousegrabber.run(function(_mouse)
        if not c.valid then return false end

        for _, v in ipairs(_mouse.buttons) do
            if v then
                prev_coords = { x = _mouse.x, y = _mouse.y }
                local new_mwfact
                if orientation == 'vertical' then
                    new_mwfact = 1 - (_mouse.x - wa.x) / wa.width * 2
                else
                    new_mwfact = 1 - (_mouse.y - wa.y) / wa.height * 2
                end
                c.screen.selected_tag.master_width_factor = math.min(math.max(new_mwfact, 0.01), 0.99)
                return true
            end
        end
        return prev_coords.x == _mouse.x and prev_coords.y == _mouse.y
    end, cursor)
end

function lain.layout.centerwork.mouse_resize_handler(c, corner, x, y)
    return centerwork_mouse_resize_handler(c, corner, x, y, 'vertical')
end

function lain.layout.centerwork.horizontal.mouse_resize_handler(c, corner, x, y)
    return centerwork_mouse_resize_handler(c, corner, x, y, 'horizontal')
end
```

**Comment by lcpz** [comment]
Thank you, I've merged your code.

**Comment by p-himik** [comment]
@lcpz Sorry, I missed a bit - `capi` is not global, it's a variable defined at the tile layout as
```lua
local capi = {
    mouse = mouse,
    mousegrabber = mousegrabber
}
```
`mouse` and `mousegrabber` are available globally.

**Comment by lcpz** [comment]
I've already defined `local capi = capi`, and it works. But to be completeley safe, I'll just remove it.

**Comment by p-himik** [comment]
That's strange - I keep getting `attempt to index upvalue 'capi' (a nil value)` when trying to resize a client.
