### ISSUE TITLE
Can't use the keyboard layout widget without errors

### ISSUE THREAD

**Issue by RomeuG** [lcpz/lain#399]
Awesome WM info:

```
awesome v4.2-376-gb9e981ba (Human after all)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

** The issue **

I have this piece of code in my rc.lua:

```
local kbdlayoutwidget = lain.widget.contrib.kbdlayout({
	  layouts = {{layout="us"},{layout="ru"},{layout="pt"}},
	  settings = function()
		 if kbdlayout_now.variant then
			widget:set_markup(markup(orange01, kbdlayout_now.layout) .. "/" .. markup(orange01, kbdlayout_now.variant) .. " ")
		 else
		 	widget:set_markup(markup(orange01, kbdlayout_now.layout) .. " ")
		 end
	  end
})
```

And this is the error message: 

![image](https://user-images.githubusercontent.com/2325589/43743527-25195de4-99ce-11e8-8faa-df5c1e8cbf4f.png)

**Comment by lcpz** [comment]
I'm not able to replicate, here it works fine.

Probably you have some other global `idx` variable in your configuration. Link me your full `rc.lua`. Also, try patching `lain/widget/contrib/kbdlayout.lua` with this:

```diff
12a13
> local assert       = assert
47a49,50
>         local idx = kbdlayout.idx
>         assert(type(idx)=="number")
61a65
>         kbdlayout.idx = idx
```

**Comment by lcpz** [comment]
Actually, I just gave a look at [`awful.widget.keyboardlayout`](https://awesomewm.org/apidoc/classes/awful.widget.keyboardlayout.html) and realised that my widget is just redundant.

Please use the native implementation.

**Comment by lcpz** [comment]
Example usage of `awful.widget.keyboardlayout`:

```lua
-- widget creation
mykbd = awful.widget.keyboardlayout:new()

-- keybinding
awful.key({ altkey }, "Shift_L", -- Alt + left Shift
          function() mykbd.next_layout() end,
          { description = "Switch to next keyboard layout", group = "hotkeys" }),
```

**Comment by RomeuG** [comment]
Indeed. I am using the native one now. Thank you for your help.
