### ISSUE TITLE
imap widget, Thunderbird label and mail count

### ISSUE THREAD

**Issue by remche** [lcpz/lain#400]
Thunderbird uses imap labels for his tags "Important, work..." named $label1, $label2... It causes lain imap widget to have a wrong mailcount.
We could change this behaviour by changing the [gsub call](https://github.com/lcpz/lain/blob/4dbf7b9f5bb468de2003e93f5ab19371e663bfce/widget/imap.lua#L62), or changing the imap request to `STATUS INBOX (UNSEEN)` (and changing the way we parse the return, btw...).

I could write a patch, but not a lua expert though.

**Comment by lcpz** [comment]
The [request](https://github.com/lcpz/lain/blob/4dbf7b9f5bb468de2003e93f5ab19371e663bfce/widget/imap.lua#L34) is already set for `SEARCH (UNSEEN)`. You can try playing with `curl` and understand how to change its call in order make it work with Thunderbird, then report back. This is the currently used call, where each `$*` string is a variable:

```shell
curl --connect-timeout 3 -fsm 3 --url imaps://$server:$port/INBOX -u $mail:$pwd -X 'SEARCH (UNSEEN)' -k
```

**Comment by remche** [comment]
In the following case I got two unread mail and a thunderbird "Important" tagged mail.
With `SEARCH (UNSEEN)` : 

```
* SEARCH 68 71
* FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded $MDNSent Forwarded $Junk $NotJunk Junk JunkRecorded NonJunk NotJunk $label1)
```
See the $label1 at the end, it will match the gsub regexp...

With `STATUS INBOX (UNSEEN)` : 

```
* STATUS "INBOX" (UNSEEN 2)
```
In this case, we could parse the return with 

```lua
mailcount = tonumber(string.match(f, "UNSEEN (%d+)"))
```
lmk if I should do a merge request.

**Comment by lcpz** [comment]
I now understand the issue, thank you. See if a51c350 solves it.

**Comment by remche** [comment]
Sorry if I was unclear...
I'm afraid you patch wont work as it, as f:match returns string and we need integer. May be a tostring() if not too ugly way ?

**Comment by lcpz** [comment]
You don't have to be sorry.  :-)

It should be OK now in 53ebca2.

**Comment by remche** [comment]
For a weird reason, my imaps server (Zimbra) sometimes answer a null string when I have no unread mail (and sometime `STATUS "INBOX" (UNSEEN 0`)...
I have to use an ugly `mailcount = tonumber(string.match(f, "UNSEEN (%d+)")) or 0` ....

**Comment by lcpz** [comment]
The precondition is that the server always replies in the `STATUS "INBOX" (UNSEEN %d)` format, so that is a Zimbra issue you have to handle in your configuration.
