### ISSUE TITLE
Calendar widget dates are not aligned

### ISSUE THREAD

**Issue by xelkarin** [lcpz/lain#401]
I've been using the awesome-copycat themes for a while now, and this has been an issue on both my laptop and desktop system for as long as I've been using it. The dates on the calendar widget don't align correctly as shown in the image below.

![lain_calendar](https://user-images.githubusercontent.com/680767/45451110-92d36300-b686-11e8-9afd-824d19b7feb0.png)

I'm running Gentoo Linux and my system calendar (`/usr/bin/cal`) is the one included with `util-linux-2.32`.

`awesome -v`
> awesome v4.2 (Human after all)
>  • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
>  • D-Bus support: ✔
>  • execinfo support: ✔
>  • xcb-randr version: 1.6
>  • LGI version: 0.9.0

`lua -v`
> Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

**Comment by xelkarin** [comment]
Xorg Log

https://gist.github.com/xelkarin/8cefbd46b831a20c8744f3aa77a88462

**Comment by lcpz** [comment]
You need a [monospaced](https://github.com/lcpz/lain/wiki/calendar#notes) font for the notification. Example: 

```lua
lain.widget.calendar {
    -- [...]
    notification_preset = {
        font = "YourMonospacedFont 11", 
        -- [...]
    }
 }
```

https://github.com/lcpz/lain/issues/17
