### ISSUE TITLE
Can't get alsa widget working

### ISSUE THREAD

**Issue by rain0r** [lcpz/lain#403]
I can't get the lain alsa-widget working. This is in my theme.lua:

    theme.volume = lain.widget.alsa({
        settings = function()
            header = " Vol "
            vlevel  = volume_now.level
            
            if volume_now.status == "off" then
                vlevel = vlevel .. "M "
            else
                vlevel = vlevel .. " "
            end
    
            widget:set_markup(markup.font(theme.font, markup(gray, header) .. markup(white, vlevel)))
        end
    })

amixer output:

    ~$ amixer -c 1 scontents
    Simple mixer control 'Master',0
      Capabilities: pvolume pvolume-joined pswitch pswitch-joined
      Playback channels: Mono
      Limits: Playback 0 - 64
      Mono: Playback 64 [100%] [0.00dB] [on]
    Simple mixer control 'Headphone',0
      Capabilities: pvolume pswitch
      Playback channels: Front Left - Front Right
      Limits: Playback 0 - 64
      Mono:
      Front Left: Playback 0 [0%] [-64.00dB] [on]
      Front Right: Playback 0 [0%] [-64.00dB] [on]
    Simple mixer control 'PCM',0
      Capabilities: pvolume
      Playback channels: Front Left - Front Right
      Limits: Playback 0 - 255
      Mono:
      Front Left: Playback 255 [100%] [0.00dB]
      Front Right: Playback 255 [100%] [0.00dB]
    Simple mixer control 'Front',0
      Capabilities: pvolume pswitch
      Playback channels: Front Left - Front Right
      Limits: Playback 0 - 64
      Mono:
      Front Left: Playback 64 [100%] [0.00dB] [on]
      Front Right: Playback 64 [100%] [0.00dB] [on]
    Simple mixer control 'Front Mic',0
      Capabilities: pvolume pswitch
      Playback channels: Front Left - Front Right
      Limits: Playback 0 - 31
      Mono:
      Front Left: Playback 0 [0%] [-34.50dB] [on]
      Front Right: Playback 0 [0%] [-34.50dB] [on]
    Simple mixer control 'Front Mic Boost',0
      Capabilities: volume
      Playback channels: Front Left - Front Right
      Capture channels: Front Left - Front Right
      Limits: 0 - 3
      Front Left: 0 [0%] [0.00dB]
      Front Right: 0 [0%] [0.00dB]
    Simple mixer control 'Surround',0
      Capabilities: pvolume pswitch
      Playback channels: Front Left - Front Right
      Limits: Playback 0 - 64
      Mono:
      Front Left: Playback 0 [0%] [-64.00dB] [off]
      Front Right: Playback 0 [0%] [-64.00dB] [off]
    Simple mixer control 'Center',0
      Capabilities: pvolume pvolume-joined pswitch pswitch-joined
      Playback channels: Mono
      Limits: Playback 0 - 64
      Mono: Playback 0 [0%] [-64.00dB] [off]
    Simple mixer control 'LFE',0
      Capabilities: pvolume pvolume-joined pswitch pswitch-joined
      Playback channels: Mono
      Limits: Playback 0 - 64
      Mono: Playback 0 [0%] [-64.00dB] [off]
    Simple mixer control 'Line',0
      Capabilities: pvolume pswitch
      Playback channels: Front Left - Front Right
      Limits: Playback 0 - 31
      Mono:
      Front Left: Playback 0 [0%] [-34.50dB] [off]
      Front Right: Playback 0 [0%] [-34.50dB] [off]
    Simple mixer control 'Line Boost',0
      Capabilities: volume
      Playback channels: Front Left - Front Right
      Capture channels: Front Left - Front Right
      Limits: 0 - 3
      Front Left: 0 [0%] [0.00dB]
      Front Right: 0 [0%] [0.00dB]
    Simple mixer control 'Capture',0
      Capabilities: cvolume cswitch
      Capture channels: Front Left - Front Right
      Limits: Capture 0 - 46
      Front Left: Capture 29 [63%] [13.00dB] [on]
      Front Right: Capture 29 [63%] [13.00dB] [on]
    Simple mixer control 'Capture',1
      Capabilities: cvolume cswitch
      Capture channels: Front Left - Front Right
      Limits: Capture 0 - 46
      Front Left: Capture 0 [0%] [-16.00dB] [off]
      Front Right: Capture 0 [0%] [-16.00dB] [off]
    Simple mixer control 'Auto-Mute Mode',0
      Capabilities: enum
      Items: 'Disabled' 'Enabled'
      Item0: 'Enabled'
    Simple mixer control 'Channel Mode',0
      Capabilities: enum
      Items: '2ch' '4ch' '6ch'
      Item0: '2ch'
    Simple mixer control 'Digital',0
      Capabilities: cvolume
      Capture channels: Front Left - Front Right
      Limits: Capture 0 - 120
      Front Left: Capture 34 [28%] [-13.00dB]
      Front Right: Capture 34 [28%] [-13.00dB]
    Simple mixer control 'Input Source',0
      Capabilities: cenum
      Items: 'Front Mic' 'Rear Mic' 'Line'
      Item0: 'Front Mic'
    Simple mixer control 'Input Source',1
      Capabilities: cenum
      Items: 'Front Mic' 'Rear Mic' 'Line'
      Item0: 'Front Mic'
    Simple mixer control 'Loopback Mixing',0
      Capabilities: enum
      Items: 'Disabled' 'Enabled'
      Item0: 'Disabled'
    Simple mixer control 'Rear Mic',0
      Capabilities: pvolume pswitch
      Playback channels: Front Left - Front Right
      Limits: Playback 0 - 31
      Mono:
      Front Left: Playback 0 [0%] [-34.50dB] [off]
      Front Right: Playback 0 [0%] [-34.50dB] [off]
    Simple mixer control 'Rear Mic Boost',0
      Capabilities: volume
      Playback channels: Front Left - Front Right
      Capture channels: Front Left - Front Right
      Limits: 0 - 3
      Front Left: 0 [0%] [0.00dB]
      Front Right: 0 [0%] [0.00dB]
    

    ~$ awesome -v
    awesome v4.2 (Human after all)
     • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
     • D-Bus support: ✔
     • execinfo support: ✔
     • xcb-randr version: 1.6
     • LGI version: 0.9.0

    ~$ lua -v
    Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

The only log-entry which may be connected to this issue is:

    2018-10-17 18:03:00 W: Cannot reliably detect EOF on an GIOInputStream with this LGI version

My installed lgi version is 0.9.0.

**Comment by lcpz** [comment]
See if you can upgrade to lua-lgi >= 0.92.

Also, open a shell and paste me the output of the following:

```shell
$ lua
$ f = io.popen("amixer get Master")
$ mixer = f:read("*a")
$ f:close()
$ string.match(mixer, "([%d]+)%%.*%[([%l]*)")
```

**Comment by lcpz** [comment]
@rain0r ping

**Comment by lcpz** [comment]
@rain0r Last ping, after wich I will close for inactivity.
