### ISSUE TITLE
Partition usage notification not working

### ISSUE THREAD

**Issue by patacca** [lcpz/lain#417]
In the widget **fs** there is an option for monitoring the usage of a specified partition but it is not working properly.
at line 109 in the file widget/fs.lua you can see that we are using ```fs_now[partition].used``` instead of ```fs_now[partition].percentage```

```
        if partition and fs_now[partition] and fs_now[partition].used >= 99 then
            if not helpers.get_map(partition) then
                naughty.notify {
```

maybe it could also be useful to put another optional argument that represents the threshold at which the notification get triggered

**Comment by lcpz** [comment]
Closed by https://github.com/lcpz/lain/commit/1a40fe80f801a27e047ce29f57215eca8f84bf6f.
