### ISSUE TITLE
Weather Icons Unnecessary timezone convesrion(?)

### ISSUE THREAD

**Issue by AzureTwilight** [lcpz/lain#428]
I am not sure about it but it seems that openweather API's have changed. The icon from returned json already has the correct day/night suffix (in EST).

I searched a bit but didn't find mentions on such change but I do need to comment out the gsub line to get correct weather icons. (https://github.com/lcpz/lain/blob/724c7b9a3a27e5de2077f388832167ae91e9f29c/widget/weather.lua#L135-L139)

Could anyone verify this?

**Comment by trap000d** [comment]
Hi,
I'll test this (as author of this kludge :)
Indeed, I've noticed of wrong icon too several days ago on my work desktop, but had no opportunity to perform debug yet - full test takes 24 hours (there are several combinations of local, DST and UTC times which may cause accidental jumps to next or previous date).

**Comment by trap000d** [comment]
Well. After testing on 2 different devices for 24 hours seems all looks good. I've just created PR.
