### ISSUE TITLE
temp widget just shows N/A

### ISSUE THREAD

**Issue by Electrux** [lcpz/lain#433]
Hello,
The temp widget since 025508ce835c3a83484b4d32c179347e51498e9f uses `/sys/devices` directory exclusively and hence, does not work for me because apparently, I do not have a `/sys/devices` directory.
I override the `tempfile` variable with the value: `/sys/class/thermal/thermal_zone1/temp` which doesn't work because the `temp_now` array is only populated with `/sys/devices` search results.
Please fix this issue.

Thanks :)
Awesome widgets btw <3

**Comment by lcpz** [comment]
`/sys/class/thermal/thermal_zone1` is a symbolic link. On your machine, which folder does it point to?

**Comment by Electrux** [comment]
oh shoot. I didn't check that, my bad. Sorry for the trouble.
It actually points to `/sys/devices/thermal/thermal_zone1/`.
Thank you very much :)
Closing this.
