### ISSUE TITLE
widgets.cal last two weeks aren't shown

### ISSUE THREAD

**Issue by sprnza** [lcpz/lain#436]
```
dell ➜  ~ awesome -v
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
dell ➜  ~ lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
```
No errors on Awesomewm's stdout (except missing icons but it's intended).

calendar's config:
```
cal = lain.widget.cal({attach_to = {txtclock}, followtag = true, week_number = "left", notification_preset = {fg = theme.text_dark,bg = theme.bg_normal, border_color = theme.highlight_light, font = "Liberation Mono 11", position = "bottom_left", width= 350}, icons = "/"})
```

Here how it looks like:
![02-08-2019-10:34-scrot](https://user-images.githubusercontent.com/1968839/62352712-80b61980-b511-11e9-8717-8e5efdab5c4c.jpg)

**Comment by last5bits** [comment]
You might want to try downgrading pango as described in awesomeWM/awesome/issues/2844.

**Comment by sprnza** [comment]
Thanks @last5bits! Fixed by downgrading and upgrading pango.
