### ISSUE TITLE
Make centerwork focus/swap behave like other layouts

### ISSUE THREAD

**Issue by nevillelyh** [lcpz/lain#447]
Hi, this is more of a question/asking for feedback. I just switched from Xmonad, added your centerwork layout and a few widgets and really dig them so far. Great work, thanks!

Regarding the centerwork focus/swap behavior, I hacked a bit and made them more consistent with other layouts, i.e. mod-j/k and mod-shift-j/k for focus/swap previous/next based on window position.

I'm super new to Lua & awesome and would greatly appreciate feedback. Happy to submit a PR too if you think it's something that's worth contributing back.

https://github.com/nevillelyh/dotfiles/commit/5c51374cef455a914ee75a2b1fc825c3cab0dc41

**Comment by lcpz** [comment]
Hi, please make a PR to facilitate me and others giving it a try.

**Comment by nevillelyh** [comment]
Thanks. Just created #448.
