### ISSUE TITLE
Wrong variable name in net widget wiki

### ISSUE THREAD

**Issue by Zwo1in** [lcpz/lain#453]
Hi,
I came here as a newcommer to awesome and to lua, I use awesome for 2 days yet. I've just literally starred for a couple of minutes trying to figure out what `netdowninfo` is :)

``` lua
local mynetdown = wibox.widget.textbox()
local mynetup = lain.widget.net {
    settings = function()
        widget:set_markup(net_now.sent)
        netdowninfo:set_markup(net_now.received)
    end
}
```

I would also like to thank you for this awesome work. I have a hard time deepdiving into awesome and lua world and reading through this code is just a great learning resource. It is powerful yet simple :+1:
Regards :)

**Comment by lcpz** [comment]
It's a typo, it should be:

``` diff
local mynetdown = wibox.widget.textbox()
local mynetup = lain.widget.net {
    settings = function()
        widget:set_markup(net_now.sent)
-        netdowninfo:set_markup(net_now.received)
+        mynetdown:set_markup(net_now.received)
    end
}
```
I fixed the wiki. Thank you for notifying me.
