### ISSUE TITLE
After updating to latest lain version, reshift stopped working (attempt to call a nil value)

### ISSUE THREAD

**Issue by finex** [lcpz/lain#477]
**Output of `awesome -v`:**
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Output of `lua -v`:**
```
Lua 5.4.1  Copyright (C) 1994-2020 Lua.org, PUC-Rio
```

**Actual behaviour:**
I've setup redshift widget using the wiki instructions. It worked fine until latest update.
When awesome starts I've the following error:

```
/usr/share/lua/5.3/lain/widget/contrib/redshift.lua:50: attempt to call a nil value (method 'buttons')

stack traceback:
  /usr/share/lua/5.3/lain/widget/contrib/redshift.lua:50: in function 'lain.widget.contrib.redshift.attach'
```

**Comment by edubart** [comment]
This happened to me too. I had to disable redshift widget for now.

**Comment by lcpz** [comment]
Sorry guys, I forgot to update the wiki yesterday. It is [done](https://github.com/lcpz/lain/wiki/redshift) now.

You have to use the dot instead of the colon to call the functions.
