### ISSUE TITLE
Why not show layout icon?

### ISSUE THREAD

**Issue by zdmgmail** [lcpz/lain#478]
sorry write wrong , please delete this...

**Comment by lcpz** [comment]
Hi, do not worry about it!

Feel free to explain what was your issue and how you solved it, so that others might benefit from it.

And if you have any questions, I am here to help.

**Comment by zdmgmail** [comment]
> Hi, do not worry about it!
> 
> Feel free to explain what was your issue and how you solved it, so that others might benefit from it.
> 
> And if you have any questions, I am here to help.

 I copy rc.lua to ~/.config/awesome/rc.lua , 
theme.lua to ~/.config/awesome/themes/default/theme.lua 

but forget to change the position in rc.lua

so I change this in rc.lua and solved

```
-- beautiful.init(gears.filesystem.get_themes_dir() .. "default/theme.lua")
beautiful.init(os.getenv("HOME") .. "/.config/awesome/themes/default/theme.lua")
```
