### ISSUE TITLE
widgets.cal week numbers are going wild

### ISSUE THREAD

**Issue by seqizz** [lcpz/lain#487]
Hi there,

First of all, thanks for all of this, I'm using most of it.

Calendar widget seems to have some confusion when I enable week numbers:

![image](https://user-images.githubusercontent.com/307899/107857857-44b38280-6e31-11eb-93f1-db63d32b85be.png)

Also non-full weeks counts as two different week, does not look right:

![image](https://user-images.githubusercontent.com/307899/107857879-7298c700-6e31-11eb-9237-4386b02f6728.png)

![image](https://user-images.githubusercontent.com/307899/107857883-7d535c00-6e31-11eb-87bd-1d893bc631f1.png)

Feel free to close if you think this is an issue about the environment :crossed_fingers: I've tried to understand the code, but the calculation blew my mind..

awesome version:
```
awesome 4.3 (Too long)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: [string "return require('lgi.version')"]:1: module 'lgi.version' not found:
        no field package.preload['lgi.version']
        no file '/usr/share/lua/5.2/lgi/version.lua'
        no file '/usr/share/lua/5.2/lgi/version/init.lua'
        no file '/usr/lib/lua/5.2/lgi/version.lua'
        no file '/usr/lib/lua/5.2/lgi/version/init.lua'
        no file './lgi/version.lua'
        no file '/usr/lib/lua/5.2/lgi/version.so'
        no file '/usr/lib/lua/5.2/loadall.so'
        no file './lgi/version.so'
        no file '/usr/lib/lua/5.2/lgi.so'
        no file '/usr/lib/lua/5.2/loadall.so'
        no file './lgi.so'
```

lua version: 5.2.4

**Comment by lcpz** [comment]
Hi, thank you for your notifying me, I can replicate the issue.

[This](https://github.com/lcpz/lain/blob/master/widget/cal.lua#L70-L83) is the culprit part of the code. In particular, the week number is defined in `notifytable[2]`. Feel free to give it a look. I will try myself ASAP.
