### ISSUE TITLE
Weather forecast stopped working due to api changes

### ISSUE THREAD

**Issue by cyberpunkrocker-zero** [lcpz/lain#493]
Weather forecast (weather.lua) as such stopped working some time ago. It seems that the daily forecast in Openweathermap is currently available only for paid subscibers :( ([https://openweathermap.org/api](url))

**Comment by trap000d** [comment]
See my PR #492

**Comment by cyberpunkrocker-zero** [comment]
Thanks @trap000d , after applying your changes and getting my own API key weather.lua is working again.
