### ISSUE TITLE
Cal widget fails on awesome-luajit due to UTF8 requeriment

### ISSUE THREAD

**Issue by edubart** [lcpz/lain#503]
I use awesome with luajit, and luajit does not have the UTF-8 module, a recent change in `cal.lua` is requiring utf8, but the global `utf8` is `nil` on luajit, so the cal widget generate errors when I hover it.

```
Oops, an error happened!
../lain/widget/cal.lua:64: attempt to index upvalue 'utf8' (a nil value)
```

**Comment by pmsdrh** [comment]
Hi! you can remove this 
:sub(1, utf8.offset(1, 3)) 
(line 64)

**Comment by razamatan** [comment]
this is a problem for anyone not using lua 5.3+.

the fix is to undo https://github.com/lcpz/lain/commit/3a6882af54dd4bb5f0fec3567dab2b5b64dec4fe locally...
