### ISSUE TITLE
Centerwork layout not keeping first client in center

### ISSUE THREAD

**Issue by whoracle** [lcpz/lain#521]
Starting with an empty tag, I open one client (e.g. text editor). This client stays in center as expected.
On spawning another client (e.g. urxvt), the new client will be placed in center and the previous one will be pushed to the side.

* output of `awesome -v` and `lua -v`
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
```
Lua 5.4.3  Copyright (C) 1994-2021 Lua.org, PUC-Rio
```
```
lain at commit  4933d6cb27390776a21c659020d8ba1f4a027624 lain (heads/master)
```

* expected behavior and actual behavior
First client should stay in center after opening another client

* steps to reproduce the problem
install awesome, awesome-copycats theme steamburn and set one of the tags to use centerwork layout

Screenshots:
[One client](https://img.lynxcore.org/one_client.png)
[Two clients](https://img.lynxcore.org/two_clients.png)

I can provide rc.lua and my modified theme.lua if needed.

**Comment by whoracle** [comment]
Thanks, the line `callback = awful.client.setslave,` was what was needed. Don't know if that's new or if I threw it out of my config in a fit of madness at some point, but adding that restored the original behaviour.

**Comment by lcpz** [comment]
That line was also missing in the `rc.lua.template` of `awesome-copycats`, so I [added](https://github.com/lcpz/awesome-copycats/commit/c187bed3dfab1d5a15374a61d75814c280c38ac9) it. Thank you for spotting this, @keslerm.
